export const rowHeight = {
    'short': '32px',
    'medium': '56px',
    'tall': '88px',
    'extra': '128px',
}

export const fieldTypes = [
    'Single Line Text',
    'Long Text',
    'Attachment',
    'Checkbox',
    'Multiple select',
    'Single select',
    'User',
    'Date',
    'Phone number',
    'Email',
    'URL',
    'Number',
    'Currency',
    'Percent',
    'Duration',
    'Rating',
    'Formula',
    'Rollup',
    'Count',
    'Lookup',
    'Created time',
    'Last modified time',
    'Created by',
    'Last modified by',
    'Autonumber',
    'Barcode',
    'Button',
];